### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by BasharAG** [mhernan88/deep_arb#1]
I tried running main.py, but I got the following error:

ImportError: No module named scripts.downloader.downloader_run

Can you add a requirements files or list the required dependencies.

**Comment by mhernan88** [comment]
Thanks for the feedback. Will work on fixing that and adding a dependencies.txt file.

Note that I just did the initial commit, so this is very much still a work-in-progress (in other words, as-of the writing of this comment, only the symbol downloader, price downloader, and distance calculation modules are finished. The actual backtester still needs to be added).

**Comment by mhernan88** [comment]
Dependencies.txt has been added.

Re-open this issue if you continue to have issues with imports.
